/**
 * Jeju Best 10 - Gourmet AI Research Lab Data
 * AI-analyzed restaurant entries for the Best 10 report.
 */

export interface RestaurantEntry {
  id: string;
  nameEn: string;
  nameKo: string;
  nameJa: string;
  nameZh: string;
  category: string;
  address: string;
  aiScore: number;
  sentimentPositive: number;
  sentimentNegative: number;
  localPopularity: 'Verified by data' | 'High' | 'Moderate';
  imageSrc: string;
  imageAlt: string;
}

export const JEJU_BEST_10_DATA: readonly RestaurantEntry[] = [
  {
    id: '1',
    nameEn: 'Black Pork Street Hall',
    nameKo: '흑돼지 거리 홀',
    nameJa: '黒豚通りホール',
    nameZh: '黑猪肉街大厅',
    category: 'Korean BBQ',
    address: 'Jeju-si, Jeju Island',
    aiScore: 98.4,
    sentimentPositive: 94,
    sentimentNegative: 6,
    localPopularity: 'Verified by data',
    imageSrc: '/images/blog/jeju-marketing/1.jpeg',
    imageAlt: 'Jeju black pork restaurant - AI-enhanced',
  },
  {
    id: '2',
    nameEn: 'Seafood Market Kitchen',
    nameKo: '해녀의 밥상',
    nameJa: '海女の食卓',
    nameZh: '海女餐桌',
    category: 'Seafood',
    address: 'Seogwipo-si, Jeju Island',
    aiScore: 96.2,
    sentimentPositive: 91,
    sentimentNegative: 9,
    localPopularity: 'Verified by data',
    imageSrc: '/images/blog/jeju-marketing/2.jpeg',
    imageAlt: 'Jeju seafood restaurant - AI-enhanced',
  },
  {
    id: '3',
    nameEn: 'Tangerine Cafe',
    nameKo: '감귤 카페',
    nameJa: 'みかんカフェ',
    nameZh: '柑橘咖啡馆',
    category: 'Cafe',
    address: 'Jeju-si, Jeju Island',
    aiScore: 95.8,
    sentimentPositive: 89,
    sentimentNegative: 11,
    localPopularity: 'High',
    imageSrc: '/images/blog/jeju-marketing/3.jpeg',
    imageAlt: 'Jeju tangerine cafe - AI-enhanced',
  },
  {
    id: '4',
    nameEn: 'Abalone Porridge House',
    nameKo: '전복죽 전문',
    nameJa: 'アワビ粥専門',
    nameZh: '鲍鱼粥专门店',
    category: 'Traditional',
    address: 'Seogwipo-si, Jeju Island',
    aiScore: 97.1,
    sentimentPositive: 93,
    sentimentNegative: 7,
    localPopularity: 'Verified by data',
    imageSrc: '/images/blog/jeju-marketing/4.jpeg',
    imageAlt: 'Jeju abalone porridge - AI-enhanced',
  },
  {
    id: '5',
    nameEn: 'Hallasan View Restaurant',
    nameKo: '한라산 전망 레스토랑',
    nameJa: '漢拏山展望レストラン',
    nameZh: '汉拿山观景餐厅',
    category: 'Fine Dining',
    address: 'Jeju-si, Jeju Island',
    aiScore: 94.6,
    sentimentPositive: 88,
    sentimentNegative: 12,
    localPopularity: 'High',
    imageSrc: '/images/blog/jeju-marketing/5.jpeg',
    imageAlt: 'Jeju Hallasan view restaurant - AI-enhanced',
  },
  {
    id: '6',
    nameEn: 'Buckwheat Noodle Master',
    nameKo: '메밀국수 명가',
    nameJa: 'そば名店',
    nameZh: '荞麦面名店',
    category: 'Noodles',
    address: 'Jeju-si, Jeju Island',
    aiScore: 93.9,
    sentimentPositive: 87,
    sentimentNegative: 13,
    localPopularity: 'Verified by data',
    imageSrc: '/images/blog/jeju-marketing/6.jpeg',
    imageAlt: 'Jeju buckwheat noodles - AI-enhanced',
  },
  {
    id: '7',
    nameEn: 'Olle Trail Bistro',
    nameKo: '올레길 비스트로',
    nameJa: 'オルレビストロ',
    nameZh: '偶来小路小酒馆',
    category: 'Bistro',
    address: 'Seogwipo-si, Jeju Island',
    aiScore: 92.4,
    sentimentPositive: 85,
    sentimentNegative: 15,
    localPopularity: 'Moderate',
    imageSrc: '/images/blog/jeju-marketing/7.jpeg',
    imageAlt: 'Jeju Olle trail bistro - AI-enhanced',
  },
  {
    id: '8',
    nameEn: 'Fresh Sashimi Harbor',
    nameKo: '횟집 항구',
    nameJa: '刺身港',
    nameZh: '生鱼片港',
    category: 'Seafood',
    address: 'Jeju-si, Jeju Island',
    aiScore: 97.8,
    sentimentPositive: 95,
    sentimentNegative: 5,
    localPopularity: 'Verified by data',
    imageSrc: '/images/blog/jeju-marketing/8.jpeg',
    imageAlt: 'Jeju fresh sashimi - AI-enhanced',
  },
  {
    id: '9',
    nameEn: 'Organic Farm Table',
    nameKo: '유기농 팜 테이블',
    nameJa: 'オーガニックファームテーブル',
    nameZh: '有机农场餐桌',
    category: 'Farm-to-Table',
    address: 'Jeju-si, Jeju Island',
    aiScore: 91.2,
    sentimentPositive: 82,
    sentimentNegative: 18,
    localPopularity: 'Moderate',
    imageSrc: '/images/blog/jeju-marketing/9.jpeg',
    imageAlt: 'Jeju organic farm restaurant - AI-enhanced',
  },
  {
    id: '10',
    nameEn: 'Jeju Omegi Rice',
    nameKo: '제주 오메기떡',
    nameJa: '済州オメギ餅',
    nameZh: '济州欧麦糕',
    category: 'Traditional',
    address: 'Jeju-si, Jeju Island',
    aiScore: 96.5,
    sentimentPositive: 90,
    sentimentNegative: 10,
    localPopularity: 'Verified by data',
    imageSrc: '/images/blog/jeju-marketing/10.jpeg',
    imageAlt: 'Jeju omegi rice cake - AI-enhanced',
  },
] as const;
